name: Python CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install & Lint
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          flake8 .

      - name: Test & Validate
        run: |
          pytest --cov=app --cov-report=term --cov-fail-under=80
          if [ "$(python app.py)" != "5" ]; then exit 1; fi

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: echo "Deploying application... success!"
